<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>smarth_health.WebApi</RootNamespace>
    <UserSecretsId>5f49edd8-129f-4d21-a676-8ac72303255f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Repositories\Dairy\**" />
    <Compile Remove="Repositories\TimelineItem\**" />
    <Compile Remove="Repositories\Timeline\**" />
    <Compile Remove="Repositories\User\**" />
    <Content Remove="Repositories\Dairy\**" />
    <Content Remove="Repositories\TimelineItem\**" />
    <Content Remove="Repositories\Timeline\**" />
    <Content Remove="Repositories\User\**" />
    <EmbeddedResource Remove="Repositories\Dairy\**" />
    <EmbeddedResource Remove="Repositories\TimelineItem\**" />
    <EmbeddedResource Remove="Repositories\Timeline\**" />
    <EmbeddedResource Remove="Repositories\User\**" />
    <None Remove="Repositories\Dairy\**" />
    <None Remove="Repositories\TimelineItem\**" />
    <None Remove="Repositories\Timeline\**" />
    <None Remove="Repositories\User\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avans.Identity.DapperOrm" Version="1.0.3" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="8.0.0" />
  </ItemGroup>

</Project>
